// <auto-generated />
using System;
using LabConnectPortal.Api.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabConnectPortal.Api.Infrastructure.Migrations
{
    [DbContext(typeof(LabConnectDbContext))]
    [Migration("20260613083201_AddJobApplication")]
    partial class AddJobApplication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.CenterProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CenterType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("EmployeeCount")
                        .HasColumnType("int");

                    b.Property<int?>("EstablishedYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<int?>("LabCode")
                        .HasColumnType("int");

                    b.Property<string>("LicensePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NationalCardPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("LabCode")
                        .IsUnique()
                        .HasFilter("[LabCode] IS NOT NULL AND [CenterType] = 0");

                    b.HasIndex("OwnerUserId")
                        .IsUnique()
                        .HasFilter("[OwnerUserId] IS NOT NULL AND [CenterType] = 1");

                    b.ToTable("CenterProfiles", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.EducationalBackground", b =>
                {
                    b.Property<Guid>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DegreeLevel")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsCurrentlyStudying")
                        .HasColumnType("bit");

                    b.Property<int?>("StartYear")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EducationId");

                    b.HasIndex("UserId");

                    b.ToTable("EducationalBackgrounds", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobApplication", b =>
                {
                    b.Property<Guid>("JobApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicantUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewNotes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitLocation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("VisitScheduledAt")
                        .HasColumnType("datetime2");

                    b.HasKey("JobApplicationId");

                    b.HasIndex("ApplicantUserId");

                    b.HasIndex("JobPostingId", "ApplicantUserId")
                        .IsUnique();

                    b.ToTable("JobApplications", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobCategory", b =>
                {
                    b.Property<int>("JobCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("JobCategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("JobCategories", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPostingBenefit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BenefitText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobPostingId");

                    b.ToTable("JobPostingBenefits", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPostingContractType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ContractType")
                        .HasColumnType("int");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobPostingId", "ContractType")
                        .IsUnique();

                    b.ToTable("JobPostingContractTypes", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPostingEssentialSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("JobPostingId", "SkillId")
                        .IsUnique();

                    b.ToTable("JobPostingEssentialSkills", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPostingPersonalTrait", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("TraitText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("JobPostingId");

                    b.ToTable("JobPostingPersonalTraits", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPostingRequest", b =>
                {
                    b.Property<Guid>("JobPostingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenderRequirement")
                        .HasColumnType("int");

                    b.Property<int>("JobCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MilitaryServiceRequirement")
                        .HasColumnType("int");

                    b.Property<int>("MinimumDegreeLevel")
                        .HasColumnType("int");

                    b.Property<int>("MinimumWorkExperienceYears")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SalaryRangeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobPostingId");

                    b.HasIndex("JobCategoryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("SalaryRangeId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("JobPostingRequests", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MinimumSalaryId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("MinimumSalaryId");

                    b.ToTable("JobPreferences", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPreferenceContractType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ContractType")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ContractType")
                        .IsUnique();

                    b.ToTable("JobPreferenceContractTypes", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPreferenceJobCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("JobCategoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobCategoryId");

                    b.HasIndex("UserId", "JobCategoryId")
                        .IsUnique();

                    b.ToTable("JobPreferenceJobCategories", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPreferenceProvince", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("UserId", "ProvinceId")
                        .IsUnique();

                    b.ToTable("JobPreferenceProvinces", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPreferenceSeniorityLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SeniorityLevel")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SeniorityLevel")
                        .IsUnique();

                    b.ToTable("JobPreferenceSeniorityLevels", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.LanguageName", b =>
                {
                    b.Property<int>("LanguageNameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageNameId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LanguageNameId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LanguageNames", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.OrganizationLocation", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LocationId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("UserId", "LocationName")
                        .IsUnique();

                    b.ToTable("OrganizationLocations", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MobileNumber", "Purpose", "IsUsed");

                    b.ToTable("OtpCodes", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProvinceId");

                    b.HasIndex("ProvinceName")
                        .IsUnique();

                    b.ToTable("Provinces", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.SalaryRange", b =>
                {
                    b.Property<int>("SalaryRangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaryRangeId"));

                    b.Property<string>("SalaryRangeDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SalaryRangeId");

                    b.HasIndex("SalaryRangeDescription")
                        .IsUnique();

                    b.ToTable("SalaryRanges", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SkillId");

                    b.HasIndex("SkillName")
                        .IsUnique();

                    b.ToTable("Skills", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmailConfirmationToken")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LabCode")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("MobileConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("LabCode");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("MobileNumber", "UserType")
                        .IsUnique();

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.UserLanguage", b =>
                {
                    b.Property<Guid>("UserLanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LanguageNameId")
                        .HasColumnType("int");

                    b.Property<int?>("ProficiencyLevel")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserLanguageId");

                    b.HasIndex("LanguageNameId");

                    b.HasIndex("UserId", "LanguageNameId")
                        .IsUnique();

                    b.ToTable("UserLanguages", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("UserNotifications", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AboutMe")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("EmploymentStatus")
                        .HasColumnType("int");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<int?>("MilitaryServiceStatus")
                        .HasColumnType("int");

                    b.Property<string>("MobilePhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ProfilePhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("ResumeFileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ResumeFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("ResumeFileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ResumeUploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("UserProfiles", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Role")
                        .IsUnique();

                    b.ToTable("UserRoles", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.UserSkill", b =>
                {
                    b.Property<Guid>("UserSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ProficiencyLevel")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserSkillId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId", "SkillId")
                        .IsUnique();

                    b.ToTable("UserSkills", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.WorkExperience", b =>
                {
                    b.Property<Guid>("WorkExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("EndMonth")
                        .HasColumnType("int");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsCurrentlyEmployed")
                        .HasColumnType("bit");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("StartMonth")
                        .HasColumnType("int");

                    b.Property<int?>("StartYear")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WorkExperienceId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkExperiences", "dbo");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.EducationalBackground", b =>
                {
                    b.HasOne("LabConnectPortal.Api.Domain.Entities.User", "User")
                        .WithMany("EducationalBackgrounds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobApplication", b =>
                {
                    b.HasOne("LabConnectPortal.Api.Domain.Entities.User", "ApplicantUser")
                        .WithMany("JobApplications")
                        .HasForeignKey("ApplicantUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabConnectPortal.Api.Domain.Entities.JobPostingRequest", "JobPosting")
                        .WithMany("Applications")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicantUser");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPostingBenefit", b =>
                {
                    b.HasOne("LabConnectPortal.Api.Domain.Entities.JobPostingRequest", "JobPosting")
                        .WithMany("Benefits")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPostingContractType", b =>
                {
                    b.HasOne("LabConnectPortal.Api.Domain.Entities.JobPostingRequest", "JobPosting")
                        .WithMany("ContractTypes")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPostingEssentialSkill", b =>
                {
                    b.HasOne("LabConnectPortal.Api.Domain.Entities.JobPostingRequest", "JobPosting")
                        .WithMany("EssentialSkills")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabConnectPortal.Api.Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobPosting");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPostingPersonalTrait", b =>
                {
                    b.HasOne("LabConnectPortal.Api.Domain.Entities.JobPostingRequest", "JobPosting")
                        .WithMany("PersonalTraits")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPostingRequest", b =>
                {
                    b.HasOne("LabConnectPortal.Api.Domain.Entities.JobCategory", "JobCategory")
                        .WithMany()
                        .HasForeignKey("JobCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabConnectPortal.Api.Domain.Entities.OrganizationLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabConnectPortal.Api.Domain.Entities.SalaryRange", "SalaryRange")
                        .WithMany()
                        .HasForeignKey("SalaryRangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabConnectPortal.Api.Domain.Entities.User", "User")
                        .WithMany("JobPostings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobCategory");

                    b.Navigation("Location");

                    b.Navigation("SalaryRange");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPreference", b =>
                {
                    b.HasOne("LabConnectPortal.Api.Domain.Entities.SalaryRange", "MinimumSalary")
                        .WithMany()
                        .HasForeignKey("MinimumSalaryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LabConnectPortal.Api.Domain.Entities.User", "User")
                        .WithOne("JobPreference")
                        .HasForeignKey("LabConnectPortal.Api.Domain.Entities.JobPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MinimumSalary");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPreferenceContractType", b =>
                {
                    b.HasOne("LabConnectPortal.Api.Domain.Entities.JobPreference", "JobPreference")
                        .WithMany("AcceptableContractTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPreference");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPreferenceJobCategory", b =>
                {
                    b.HasOne("LabConnectPortal.Api.Domain.Entities.JobCategory", "JobCategory")
                        .WithMany()
                        .HasForeignKey("JobCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabConnectPortal.Api.Domain.Entities.JobPreference", "JobPreference")
                        .WithMany("JobCategories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobCategory");

                    b.Navigation("JobPreference");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPreferenceProvince", b =>
                {
                    b.HasOne("LabConnectPortal.Api.Domain.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabConnectPortal.Api.Domain.Entities.JobPreference", "JobPreference")
                        .WithMany("PreferredProvinces")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPreference");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPreferenceSeniorityLevel", b =>
                {
                    b.HasOne("LabConnectPortal.Api.Domain.Entities.JobPreference", "JobPreference")
                        .WithMany("SeniorityLevels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPreference");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.OrganizationLocation", b =>
                {
                    b.HasOne("LabConnectPortal.Api.Domain.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabConnectPortal.Api.Domain.Entities.User", "User")
                        .WithMany("OrganizationLocations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.UserLanguage", b =>
                {
                    b.HasOne("LabConnectPortal.Api.Domain.Entities.LanguageName", "LanguageName")
                        .WithMany()
                        .HasForeignKey("LanguageNameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabConnectPortal.Api.Domain.Entities.User", "User")
                        .WithMany("UserLanguages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LanguageName");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("LabConnectPortal.Api.Domain.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LabConnectPortal.Api.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("LabConnectPortal.Api.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("LabConnectPortal.Api.Domain.Entities.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.UserSkill", b =>
                {
                    b.HasOne("LabConnectPortal.Api.Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabConnectPortal.Api.Domain.Entities.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.WorkExperience", b =>
                {
                    b.HasOne("LabConnectPortal.Api.Domain.Entities.User", "User")
                        .WithMany("WorkExperiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPostingRequest", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Benefits");

                    b.Navigation("ContractTypes");

                    b.Navigation("EssentialSkills");

                    b.Navigation("PersonalTraits");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.JobPreference", b =>
                {
                    b.Navigation("AcceptableContractTypes");

                    b.Navigation("JobCategories");

                    b.Navigation("PreferredProvinces");

                    b.Navigation("SeniorityLevels");
                });

            modelBuilder.Entity("LabConnectPortal.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("EducationalBackgrounds");

                    b.Navigation("JobApplications");

                    b.Navigation("JobPostings");

                    b.Navigation("JobPreference");

                    b.Navigation("OrganizationLocations");

                    b.Navigation("Profile");

                    b.Navigation("Roles");

                    b.Navigation("UserLanguages");

                    b.Navigation("UserSkills");

                    b.Navigation("WorkExperiences");
                });
#pragma warning restore 612, 618
        }
    }
}
