/** Entity names that can appear in activity logs (admin filter). */
export const ACTIVITY_LOG_ADMIN_ENTITIES = [
  'Product',
  'Brand',
  'ProductCategory',
  'ProductCategoryGroup',
  'ProductAttribute',
  'ProductImage',
  'ProductExpertReview',
  'ProductCategoryAssignment',
  'ProductAttributeValue',
  'ContentGroup',
  'ContentPost',
  'SliderGroup',
  'SliderSlide',
  'SiteUsefulLink',
  'SiteSettings',
  'SiteUserPermission',
  'ProductUserReview',
  'ProductReviewReply',
  'CenterProfile',
  'SpecialOffer',
  'SpecialOfferTest',
  'SpecialOfferRequest',
  'DeviceGroup',
  'KitGroup',
  'TestInfo',
  'LabAgreement',
  'LabAgreementAttachment',
  'LabAgreementTestPrice',
  'ProductOrder',
  'ProductOrderItem',
  'User',
  'LabUserPermission',
  'OrganizationLocation',
  'JobPostingRequest',
  'JobPostingBenefit',
  'JobPostingContractType',
  'JobPostingEssentialSkill',
  'JobPostingPersonalTrait',
  'JobApplication',
  'UserProfile',
  'WorkExperience',
  'EducationalBackground',
  'UserSkill',
  'UserLanguage',
  'JobPreference',
  'Skill',
] as const;

/** Center-scoped entities typically edited from /profile. */
export const ACTIVITY_LOG_PROFILE_ENTITIES = [
  'CenterProfile',
  'SpecialOffer',
  'SpecialOfferTest',
  'SpecialOfferRequest',
  'DeviceGroup',
  'KitGroup',
  'TestInfo',
  'LabAgreement',
  'LabAgreementAttachment',
  'LabAgreementTestPrice',
  'ProductOrder',
  'ProductOrderItem',
  'User',
  'LabUserPermission',
  'OrganizationLocation',
  'JobPostingRequest',
  'JobApplication',
  'UserProfile',
  'WorkExperience',
  'EducationalBackground',
] as const;
